type User {
    name: String!
    cars: [Car] @relation
}

type Car {
    user: User!
    name: String!
    dateOfPurchase: String!
    mileageAtPurchase: Int!
    fuels: [Fuel] @relation
}

type Fuel {
    car: Car!
    date: String!
    km: Int!
    litres: Float!
    cost: Float!
}